#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayIM.NetClient
{
    using System;
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ChatLog : RazorPage
    {
        public ChatLog()
        {
        }
        public override void Execute()
        {
WriteLiteral("<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <title>聊天记录</title>\r\n    <link");

WriteLiteral(" href=\"/Scripts/layui/css/layui.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <style>body .layim-chat-main {height: auto;}</style>\r\n    <link");

WriteLiteral(" href=\"/css/layim.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n    <div");

WriteLiteral(" class=\"layim-chat-main\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" id=\"LAY_view\"");

WriteLiteral(">  \r\n            <div");

WriteLiteral(" id=\"chatLogMore\"");

WriteLiteral(" class=\"layim-chat-system\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral("><span>查看更多记录</span></div>\r\n");

WriteLiteral("            ");


#line 11 "..\..\Views\Home\ChatLog.cshtml"
            Write(Html.RenderPartial(new HistoryMessagePage()));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"LAY_page\"");

WriteLiteral(" style=\"margin: 0 10px;\"");

WriteLiteral("></div>\r\n    <script");

WriteLiteral(" src=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'#chatLogMore\')." +
"on(\'click\', function () {\r\n                console.log(\'查看更多\');\r\n            })\r" +
"\n        })\r\n        \r\n    </script>\r\n");

        }
    }
}
#pragma warning restore 1591
