#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayIM.NetClient
{
    using System;

    #line 3 "..\..\Views\Home\ChatLog.cshtml"
    using LayIM.NetClient;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ChatLog : RazorPage
    {
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\ChatLog.cshtml"
   Layout = null;
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <title>聊天记录</title>\r\n    <link");

WriteLiteral(" href=\"/Scripts/layui/css/layui.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <style>body .layim-chat-main {height: auto;}</style>\r\n    <link");

WriteLiteral(" href=\"/css/layim.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n\r\n    <div");

WriteLiteral(" class=\"layim-chat-main\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" id=\"LAY_view\"");

WriteLiteral(">  \r\n            <div");

WriteLiteral(" id=\"chatLogMore\"");

WriteLiteral(" class=\"layim-chat-system\"");

WriteLiteral("><span>查看更多记录</span></div>\r\n            <li");

WriteLiteral(" class=\"layim-chat-mine\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite><i>2016-12-05 08:31:22</i>纸飞机</cite>\r\n            " +
"    </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" alt=\"[抱抱]\"");

WriteLiteral(" title=\"[抱抱]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/25.gif\"");

WriteLiteral(" />\r\n                    <img");

WriteLiteral(" alt=\"[心]\"");

WriteLiteral(" title=\"[心]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/47.gif\"");

WriteLiteral(" /> 你好啊小美女\r\n                </div>\r\n            </li>\r\n            <li>\r\n        " +
"        <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
            <li>
                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
            <li>
                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
            <li>
                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
            <li>
                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
            <li>
                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:32</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你没发错吧？\r\n                    <img");

WriteLiteral(" alt=\"[微笑]\"");

WriteLiteral(" title=\"[微笑]\"");

WriteLiteral(" src=\"http://localhost:6357/Scripts/layui/images/face/0.gif\"");

WriteLiteral(" />\r\n                </div>\r\n            </li>\r\n            <li>\r\n               " +
" <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:38</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n                    你是谁呀亲。。我爱的是贤心！我爱的是贤心！我爱的是贤心！重要的事情要说三遍~\r\n                </" +
"div>\r\n            </li>\r\n            <li>\r\n                <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"http://tva3.sinaimg.cn/crop.0.0.512.512.180/8693225ajw8f2rt20ptykj20e80e8we" +
"u.jpg\"");

WriteLiteral(" />\r\n                    <cite>Z_子晴<i>2016-12-05 08:31:48</i></cite>\r\n           " +
"     </div>\r\n                <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(@">
                    注意：这些都是模拟数据，实际使用时，需将其中的模拟接口改为你的项目真实接口。
                    <br />该模版文件所在目录（相对于layui.js）：
                    <br />/css/modules/layim/html/chatlog.html
                </div>
            </li> 
         </ul>
    </div>

    <div");

WriteLiteral(" id=\"LAY_page\"");

WriteLiteral(" style=\"margin: 0 10px;\"");

WriteLiteral("></div>\r\n    <script");

WriteLiteral(" src=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'#chatLogMore\')." +
"on(\'click\', function () {\r\n                console.log(\'查看更多\');\r\n            })\r" +
"\n        })\r\n        \r\n    </script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
